# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tm7Jf1xv0Z0XqIxSz9EuOMLU_Bq0VwVb
"""

!pip install ultralytics
from ultralytics import YOLO

# Commented out IPython magic to ensure Python compatibility.
# %%writefile augment.yaml
# # YOLOv8 custom augmentation file
# augment:
#   hsv_h: 0.015
#   hsv_s: 0.7
#   hsv_v: 0.4
#   degrees: 10            # rotation
#   translate: 0.1
#   scale: 0.5
#   shear: 0.2
#   perspective: 0.0005
#   flipud: 0.0
#   fliplr: 0.5
#   mosaic: 1.0
#   mixup: 0.1
#   copy_paste: 0.1       # simulating occlusion
#

!pip install ultralytics
from ultralytics import YOLO

model = YOLO("yolov8n.pt")

model.train(
    data="coco128.yaml",
    epochs=20,
    imgsz=640,
    batch=16
)

!pip install ultralytics
from ultralytics import YOLO

model = YOLO("yolov8n-seg.pt")

!pip install ultralytics
from ultralytics import YOLO

!wget https://ultralytics.com/assets/coco8-seg.zip
!unzip -o coco8-seg.zip

model = YOLO("yolov8n-seg.pt")
model.train(data="coco8-seg.yaml", epochs=20, imgsz=640)

# Load the best trained model for prediction
model = YOLO("/content/runs/segment/train3/weights/best.pt")
# Run prediction on a sample image from the dataset
# Assuming 'bus.jpg' is present in 'coco8-seg/images/val'
results = model.predict(source="coco8-seg/images/val/bus.jpg", save=True, save_txt=False)